# remote_theme: janczizikow/sleek
# google_tag_manager: GTM-MJLDWPT
remote_theme: broccolini/swiss
theme_color: orange
markdown: kramdown

github_repo: zwift-beginner-resources
github_username: xkraigx

