# theme: jekyll-theme-hacker
theme: jekyll-theme-minimal
title: ZwiftyWiki
description: Recursos útiles para disfrutar de Zwift
google_tag_manager: GTM-MJLDWPT
plugins:
  - jekyll-relative-links
  - jekyll-target-blank
  - jemoji
relative_links:
  enabled: true
  collections: false
include:
  - README.md
  - trainers.md
  - maps.md
  - faqs.md
  - power101.md
  - main.md
  - troubleshooting.md
  - london.md
  - paris.md
  - innsbruck.md
  - richmond.md
  - bologna.md
  - france.md
  - critcity.md
  - yorkshire.md
  - watopia.md
