theme: jekyll-theme-minimal
title: Recursos Zwift
google_tag_manager: GTM-MJLDWPT
plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - trainers.md
  - maps.md
  - faqs.md
  - power101.md
  - main.md
  - troubleshooting.md

