remote_theme: janczizikow/sleek
title: "Recursos Zwift"
google_tag_manager: GTM-MJLDWPT
plugins:
  - jekyll-relative-links
  - jemoji-plus
emoji_plus:
  image:
    width:20
    height:20
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - trainers.md
  - maps.md
  - faqs.md
  - power101.md
  - main.md
  - troubleshooting.md

