remote_theme: janczizikow/sleek
google_tag_manager: GTM-MJLDWPT
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - trainers.md
  - maps.md
