# remote_theme: janczizikow/sleek
# google_tag_manager: GTM-MJLDWPT
remote_theme: amitmerchant1990/reverie
name: Zwift Beginner Resources
avatar: https://upload.wikimedia.org/wikipedia/commons/c/ca/Zwf_vts_rgb_pos_blk.png

